# ----------- CONFIGURABLE START -----------
title:            "abanjara"
description:      "Design Engineer"
url:              https://abanjara.com.np # Site url, without a slash at the end.
signoff:          "abanjara" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          abanjara.com.np
    external:     false
  - name:         Bathokoshero
    url:          https://prajjowl.com.np/bathokoshero
    external:     true
  - name:         About me
    url:          abanjara.com.np/about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
